# Generated by Django 5.1.1 on 2024-09-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningmateapi', '0003_learningplan'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='learningplan',
            table='learning_plans',
        ),
    ]
