# Generated by Django 5.1.1 on 2024-09-15 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningmateapi', '0004_alter_learningplan_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningplan',
            name='name',
        ),
    ]
